### ISSUE TITLE
Publish the spec to npm

### ISSUE THREAD

**Issue by nicojs** [commonmark/CommonMark#394]
Is it possible to publish the spec to npm on each release of the spec? I would like to make a direct (dev-)dependency between [html2commonmark](https://github.com/nicojs/html2commonmark) and the spec so it is much simpler to keep my tests in sync with the examples from the spec.

Too bad that the package name `commonmark` is already taken by [commonmark.js](https://github.com/jgm/commonmark.js). Maybe we could use `commonmark-spec`?

If you agree i can create the pull request which adds a [package.json](https://docs.npmjs.com/getting-started/using-a-package.json) file. 

A question that still needs to be answered is: who will be the owner of the npm package on npmjs.com.

EDIT:
This will also allow for a dev-dependency between commonmark.js and commonmark, this way you won't have to manually copy over the spec.txt to there

**Comment by wooorm** [comment]
As an aside, I’m currently “maintaining” [commonmark.json](http://npmjs.com/commonmark.json) ([gh](https://github.com/wooorm/commonmark.json)), which contains the CommonMark input/output fixtures in JSON format. “Maintaining” in quotes because I seem to have forgotten to release 0.24...

I created it because I needed it and possible others too, but it might be better if `jgm/CommonMark`s build script produces it on every version bump, and automatically publishes it?

(P.S. is this issue about the complete `spec.txt` or just the fixtures?)

**Comment by jgm** [comment]
Would it be helpful to have a commonmark-spec package that
includes spec.txt, spec.html, and a json version of the
test cases?  As you suggest, I could add that to the release
procedure.

But maybe all that is needed is the json?

+++ Titus Wormer [Feb 16 16 00:46 ]:

**Comment by nicojs** [comment]
Yes, all i need is the json, but it makes sense to publish the entire spec as markdown/html and txt file. 

Maybe we can also add the spec as a nodejs module. Something like this:
```javascript
// tests.spec.js
var tests = [{
    "end_line": 270,
    "example": 1,
    "html": "<pre><code>foo\tbaz\t\tbim\n</code></pre>\n",
    "start_line": 265,
    "section": "Tabs",
    "markdown": "\tfoo\tbaz\t\tbim\n"
  }, ...]
exports = tests
```

Than in the package.json we could add a main `main: 'tests.spec.js'`. Than it is possible to just `require` the spec like this: `var commonmarkSpec = require('commonmark-spec');`

**Comment by puzrin** [comment]
It would be convenient to have spec in npm. For our needs (`markdown-it` develepment) text format is required. If anyone wish json - i think it's ok to include both.

- text - because it's original source, and allows to find spec line and content nearby.
- json - that can be more convenient if someone just wish to quickly load data and don't cares about source lines.

**Comment by jgm** [comment]
Do you want to send a PR with the right sort of
package.json?

+++ Vitaly Puzrin [Dec 09 16 02:51 ]:

**Comment by puzrin** [comment]
Sure, happy to help https://github.com/jgm/CommonMark/pull/444!

Need some tweaks at your side, but everything about node/npm is correct. If you wish - just copy content to final files, mention of my name is not necessary.

**Comment by jgm** [comment]
AFter some tweaks, it's published.

You have both .text and .tests (the json test cases), as
well as .version.

+++ Vitaly Puzrin [Dec 09 16 03:26 ]:

**Comment by puzrin** [comment]
I have no questions.

@nicojs ?

**Comment by jgm** [comment]
This seems to have been resolved but never closed.
