### ISSUE TITLE
Emphasis rule 14

### ISSUE THREAD

**Issue by mgeier** [commonmark/CommonMark#451]
Emphasis rule 14 in spec 0.27 states:

> An interpretation `<em><strong>...</strong></em>` is always preferred to `<strong><em>..</em></strong>`.

I don't know the motivation and I don't really care about the order, but I guess the rule should match the examples. Which it doesn't:

Example [441](http://spec.commonmark.org/0.27/#example-441) converts

```
***foo***
```

into

```
<p><strong><em>foo</em></strong></p>
```

... which is the opposite of what rule 14 says. Same for example 442.

Basically all implementations follow the example and ignore the rule, which isn't really surprising: <http://johnmacfarlane.net/babelmark2/?normalize=1&text=***..***>.

So which one should it be?

If there is a reason for the decision, it would probably be interesting to mention it in the spec?
Even more so if it's just an arbitrary decision.

And another issue I realized just when writing this issue: In one example there are three dots and in the other one there are two. This can't be right, right? (UPDATE: see #477)

**Comment by aidantwoods** [comment]
Rule 14 now says
> An interpretation `<strong><em>...</em></strong>` is always preferred to `<em><strong>..</strong></em>`.

Though I'm a little confused, because the current spec.txt has what you've put.

**Comment by aidantwoods** [comment]
From https://github.com/jgm/CommonMark/commit/0e5e95eb7fcc973128d3a2a8cddf221f3825c156

```
Previously the nesting Strong (Emph (...)) was preferred
over Emph (Strong (...)).  This change makes Emph (Strong (...))
preferred.

Note that the commonmark reference implementations
were not entirely consistent about this rule, giving
different results for

    ***hi***

and

    ***hi****

This change simplifies parsing.  It goes against the majority
of implementations, but only on something utterly trivial.
```

If this indeed utterly trivial, why make it part of the spec at all? **I don't see why an optimisation in the reference parser should have a baring on specification.** It might be better as a suggestion in the parsing strategy section, but surely all declaring an ordering does is decrease the ability for implementations to declare they are fully compliant?

**Comment by jgm** [comment]
+++ Aidan Woods [May 27 17 17:16 ]:
>   If this indeed utterly trivial, why make it part of the spec at all?

The original intent was to have the spec define a total
function from sequences of unicode code points to parsed
documents.  So, no "undefined behavior."

It's not clear that this ambition is the right one to have,
since as you say it can impose constraints on
implementations for the benefit of conformity in trivial
cases.

But having undefined behavior makes it harder to provide
test cases, and may make it harder to write the spec (since
in such cases, not just ANY behavior is allowed; e.g. you
wouldn't want an implementation to produce a link in this
case; but then the range of allowed possibilities needs
to be defined).

**Comment by aidantwoods** [comment]
> But having undefined behavior makes it harder to provide
test cases, and may make it harder to write the spec (since
in such cases, not just ANY behavior is allowed; e.g. you
wouldn't want an implementation to produce a link in this
case; but then the range of allowed possibilities needs
to be defined).

I'm not sure we're talking about the same thing here – there should still of course be a requirement that and `<em>` and a `<strong>` are produced, but this particular line in the spec doesn't enforce that anyway (it relies on a conforming parser producing some ordering and then just states which is preferred).

It wouldn't be entirely unprecedented to leave the ordering up to the implementation, for example in fenced code blocks the [info string](http://spec.commonmark.org/0.27/#info-string) carries an implementation defined choice:

> The first word of the [info string](http://spec.commonmark.org/0.27/#info-string) is typically used to specify the language of the code sample, and rendered in the `class` attribute of the code tag. However, this spec does not mandate any particular treatment of the [info string](http://spec.commonmark.org/0.27/#info-string).

There are still test cases that use the info string, it just means that a parser that does not pass those specific ones can honestly state that it still conforms, because this particular detail was optional.
