### ISSUE TITLE
Example 116 expects broken HTML

### ISSUE THREAD

**Issue by ujifgc** [commonmark/CommonMark#511]
http://spec.commonmark.org/0.28/#example-116 introduced in #459 adds an example that requires to generate a broken HMTL.

Input:

```HTML
<table><tr><td>
<pre>
**Hello**,

_world_.
</pre>
</td></tr></table>
```
Expected in the spec:

```HTML
<table><tr><td>
<pre>
**Hello**,
<p><em>world</em>.
</pre></p>
</td></tr></table>
```

Suggested fix:

```HTML
<table><tr><td>
<pre>
**Hello**,
<p><em>world</em>.</p>
</pre>
</td></tr></table>
```

**Comment by jgm** [comment]
The fact that this generates invalid HTML is not in itself a problem.  You'll always be able to create invalid HTML by inserting raw HTML.  And the example is flagged as a case where you get "surprising" results; this is almost certainly not something someone would do intentionally, but it's still useful to illustrate what the spec's rules call for here.

One thing that could be changed in our current rules:  `</td>` starts a raw HTML block, per start condition 6, but `</pre>` does not.  That may be surprising, but it's due to the special treatment of pre, style, and script in the start/end conditions.

If we added a condition that a line beginning with `</pre>` starts a raw HTML block, then we'd get the result you describe above.

**Comment by jgm** [comment]
See #517 
Since I recommend there that we let `</pre>` start a raw HTML block, I'll close this.
