### ISSUE TITLE
Inability to define Anchors within document

### ISSUE THREAD

**Issue by mrmass** [commonmark/CommonMark#549]
Dear CommonMark contributors,

Unless I've missed something, I haven't found a way how to define anchors in the page to link through the content without usage of HTML. In case this is somehow possible then I'd like to report that it might not be very obvious how (based on the experience within our team & googling).

There's not a single hit found when searching for "anchor" in spec (https://spec.commonmark.org/0.28/).

All I found is following thread (https://talk.commonmark.org/t/anchors-in-markdown/247) where this is discussed for 4+ years. Instead of some sort of agile approach to support at least some basic way for this to function while the rest of the scope is discussed/voted on/etc., this thread is just filled with scope creep, opinions, votes, more scope creep, and no action.

This is kind of funny and sad at same time considering the CommonMark project is hosted on GitHub that uses their own rendering of MarkDown and therefore from the syntax in https://github.com/commonmark/CommonMark/blob/master/spec.txt the internal anchors for ToC and such actually get navigated. It also makes me wonder how would you go about this if your project wasn't actually hosted on GitHub (or if GitHub would decide to adopt CommonMark as the standard :rofl:).

We are considering using MarkDown more widely within our team for internal docs with Bitbucket repository, and so wanted to go for what seems a reasonable standard (CommonMark), however this finding really is a good reason enough to chose anything else.

I realise that you might be implementing this standard purely from your own good will or for your own needs that might not align with ours or others, so please don't consider this a rant/hate/demand, I wouldn't dare to do so when we're not paying you anything. It's just a statement.

I do appreciate the amount of effort all of the contributors must have put into getting CommonMark where it is today because despite the above, it is great initiative to work on making common grounds that work everywhere.

So in respect to all that I'm sharing this feedback for your consideration.

**Comment by jgm** [comment]
> (or if GitHub would decide to adopt CommonMark as the standard 🤣).

Actually, it has:  https://githubengineering.com/a-formal-spec-for-github-markdown/
Your comment, above, has been rendered by a slightly extended version of the commonmark reference parser.

The main aim at this point is to finish the "core" spec.  This has been slow because I've had very limited time to devote.  But in the mean time, I'd suggest using core commonmark + your own unblessed extensions.  That is still an improvement to everyone using a different set of core rules.

In the spec document, we use some simple conventions + filters to produce anchors.  Thus, you write
```
[whitespace character](@)
```
and it produces an anchor that you can link back to later using `[whitespace character]`.  This requires a bit of processing of the underlying AST, which we do using a lua wrapper around cmark and a custom filter (tools/make_spec.lua).

I understand that it is frustrating not having a consistent syntax for this yet.  If CommonMark is too minimal at this point, you could alternatively decide to use pandoc's markdown, which is well established and has facilities for producing anchors. Your docs can then be converted (using pandoc) to other formats, including commonmark, so you're not locked in.

**Comment by mrmass** [comment]
Thanks for your answer, @jgm, I understand your reasons. I wasn't aware of the comment rendering. 👍 I clearly didn't do my homework properly there 😞, I was pretty frustrated (not an excuse though) yesterday after spending quite a while struggling, unwilling to accept that anchors are not possible.

We're still experimenting, and pandoc was one of the things we looked at too, though using CommonMark seemed strictly better (well, that is if it would do all we need to). Frankly I don't like the workaround much, I'd rather just write the anchors in HTML then and wait until it gets correctly implemented. You're right that using CommonMark + a couple of our own agreed rules is better than just everyone cluelessly using whatever they want.

Another things we're also looking at is AsciiDoc - I don't personally like the way the syntax looks like but it seems to be a solid tool for the job too.

I don't know what we'll end up using or not but either way good luck with wrapping up the core release!

**Comment by Crissov** [comment]
What would help would be an agreed upon way to centrally document extensions, which @jgm should not have to do himself alone.
