### ISSUE TITLE
Standardise spoilers

### ISSUE THREAD

**Issue by sbrl** [commonmark/CommonMark#570]
With spoilers as a feature becoming an increasingly common occurrence, it makes sense to standardise them under CommonMark.

Reddit, which has recently added markdown support, uses this syntax:

`This is a >!spoiler!<`

However, Discord now supports this syntax:

`This is a ||spoiler||`

Standardising now will avoid unnecessary further fragmentation.

**Comment by Crissov** [comment]
https://talk.commonmark.org/t/what-could-a-spoiler-tag-extension-look-like/767

See this and several other threads.

**Comment by jgm** [comment]
Discussion of possible extensions should go to the forum rather than here.
I would recommend that when people need extensions like this, they first consider adopting a convention using standard commonmark syntax.  That way, standard commonmark parsers can be used, and the extension can be implemented by transforming the parse tree.  For example:
```
This is a [spoiler](!).
or
This is a [spoiler](SPOILER)
or
This is a <spoiler>spoiler</spoiler>
```

**Comment by sbrl** [comment]
Ah, I didn't know there was a forum! I did search through the issues here, but didn't find anything.

I'll take a look at those links.
