### ISSUE TITLE
Multi line break fail

### ISSUE THREAD

**Issue by mrx23dot** [commonmark/CommonMark#769]
```
## COMMON_STEPS
* test 1
\
\
\
* test 2
* test 3
```

produces
![image](https://github.com/commonmark/commonmark-spec/assets/4163396/265be779-3f36-4a4b-afd9-70c86d78d05e)

```
<li><p>test 1
<br />
<br />
\</p></li>
<li><p>test 2</p></li>
<li><p>test 3</p></li>
```

not 3 line breaks

https://spec.commonmark.org/dingus/?text=%23%23%20COMMON_STEPS%0A*%20test%201%0A%5C%0A%5C%0A%5C%0A*%20test%202%0A*%20test%203

Why make life harder? Simply allow any line breaks.

**Comment by vassudanagunta** [comment]
I think you misunderstand the semantics of `\` to be "insert a `<br>` tag here", which it is not, [per the spec](https://spec.commonmark.org/0.29/#hard-line-break):

> A line break (not in a code span or HTML tag) that is preceded by two or more spaces and does not occur at the end of a block is parsed as a hard line break (rendered in HTML as a <br /> tag)

and more specifically:

> Hard line breaks are for separating inline content within a block. Neither syntax for hard line breaks works at the end of a paragraph or other block element

That said, [Pandoc behaves the way you want](https://babelmark.github.io/?text=a%5C%0Ab%5C%0Ac%5C%0A), whether intentionally or by accident, I don't know.

**Comment by wooorm** [comment]
The semantics of HTML is also that `<br>` is only sensical *inside* paragraphs, not at the end. The user on SO you are following is wrong.

**Comment by wooorm** [comment]
Don't; because it's not a good idea.

![](https://github.com/commonmark/commonmark-spec/assets/944406/28708b27-fe05-4620-a3b4-df6e3457853f)

HTML has meaning. Markdown is for generating those things with meaning too. It's not supposed to do things without meaning.

You can still abuse HTML. And CM allows that too: you can write those br tags (even though you shouldn't) in markdown.
